ArrayList<Particle> particles; //DEFINO UN ARRAY LIST DE TAMANO INDEFINIDO Y ADEMAS VACIO, QUE SE VA A LLAMAR "particles"

float t0; //SETEO DE VARIBALE t0, COMIENZO DE EJECUCION DEL PROGRAMA

void setup() {
  

  size(500, 500); //SCREEN SIZE
  particles = new ArrayList<Particle>(); //CREO EL ARRAY LIST VACIO
  t0 = millis(); //TIEMPO DE EJECUCION DEL PROGRAMA 
  
}

void draw() {
 

  background(255); //SETEO DE FONDO DEL APP
  //DELTA TIME, TIEMPO TRANSCURRIDO DESDE EL ULTIMO FRAME
  float dt = millis() - t0;
  dt = dt/1000.0; //HAGO QUE LAS ANIMACIONES OCURRAN A UN TIEMPO DETERMINADO SIEMPRE
  
  for (int i=0; i<particles.size(); i++){ //FOR LOOP QUE SE EJECUTA 60 VECES POR SEGUNDO, ESTE DIBUJA TANTO LAS ANIMACIONES DE LAS PARTICULAS, Y ADEMAS DIBUJA LAS PARITUCLAS
    Particle p = particles.get(i); //DEFINO UN NUEVO OBJETO PARTICLE Y LE ASIGNO UNA PATICULA YA CREADA DEL ARRAY particles CADA VEZ QUE SE EJECUTA EL LOOP
    p.moveUpSquare(dt); //USO EL OBJETO OBTENIDO DEL ARRAY Y LLAMO A LA FUNCION UPDATE EN EL DELTA TIME, ASI LA ANIMACION ES SIEMPRE LA MISMA Y CONSTANTE SOBRE ESE OBJETO
    p.displaySquare(); //USO EL OBJETO OBTENIDO DEL ARRAY Y LLAMO A LA FUNCION DISPLAY PARA MOSTRAR EL OBJETO CON SU ANIMNACION
    if (p.outOfBounds()){ //SI EL OBJETO OBTENIDO DEL ARRAY SALE DE LA PANTALLA SE DESTRUYE, SE DESTRUYE PORQUE LO QUITAMOS DEL ARRAY
      particles.remove(i); 
    }
  }
  
  t0 = millis(); //OBTENGO EL NUEVO FRAME
  


}

void mouseDragged(){
   Particle part1;
   part1 = new Particle(mouseX, mouseY,int(random(10,100)),int(random(10,100)),int(random(0,360)),int(random(50,200)));
   particles.add(part1); //AGREGO ESE OBJETO AL ARRAY LIST

}
